services:
  web-books:
    build:
      context: ./book_backend
      dockerfile: Dockerfile
    command: gunicorn composites.book_api:app --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - mynetwork
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    ports:
      - 5432:5432
    networks:
      - mynetwork
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  nginx:
    build: ./gateway
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
    networks:
      - mynetwork
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - "rabbitmq_data:/data"
networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  rabbitmq_data: