services:
  web-books:
    build:
      context: ./book_backend
      dockerfile: Dockerfile
    command: gunicorn composites.book_api:app --bind 0.0.0.0:8000
    restart: unless-stopped
    depends_on:
      - db_books


  web-issues:
    build:
      context: ./issue_backend
      dockerfile: Dockerfile
    command: gunicorn composites.issue_api:app --bind 0.0.0.0:8001
    restart: unless-stopped
    depends_on:
      - db_issues

  web-issues-consumer:
    build:
      context: ./issue_backend
      dockerfile: Dockerfile
    command: python3 -m composites.consumer
    restart: unless-stopped
    depends_on:
      - db_issues





  db_books:
    image: postgres:13.0-alpine
    env_file:
      - .env.db
    ports:
      - 5555:5432

  db_issues:
    image: postgres:13.0-alpine
    env_file:
      - .env.db
    ports:
      - 4444:5432

  nginx:
    build: ./gateway
    ports:
      - 1337:80
    depends_on:
      - web

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - "rabbitmq_data:/data"

volumes:
  postgres_data:
  rabbitmq_data: